### ISSUE TITLE
[Bugs] Arch Linux下编译出错

### ISSUE THREAD

**Issue by zxp19821005** [revezone/revezone#5]
### 环境
OS : EndeavourOS x86_64 6.1.44-1-lts
DE : Cinnamon
nodejs : 18.17.0
pnpm : 8.6.11

### 编译出错
我个人想把包移植到ArchLinux的AUR，`PKGBUILD`文件内容如下：
```
# Maintainer: zxp19821005 <zxp19821005 at 163 dot com>
pkgname=revezone
pkgver=1.0.0_alpha.11
pkgrel=1
pkgdesc="A new way to use Excalidraw. A lightweight productivity tool to build Second Brain that integrates Notion-like note-taking and enhanced Excalidraw whiteboarding features."
arch=('any')
url="https://revezone.com/"
_githuburl="https://github.com/revezone/revezone"
license=('custom')
conflicts=("${pkgname}")
depends=('bash' 'electron25' 'hicolor-icon-theme')
makedepends=('nodejs' 'pnpm' 'npm')
source=("${pkgname}-${pkgver}.tar.gz::${_githuburl}/archive/refs/tags/${pkgver//_/-}.tar.gz"
    "${pkgname}.sh")
sha256sums=('de8b7ff7c81af5c83ce23d9e3f92f09350d4c115c053bd1aafb58637e7d12131'
            '2a16e120cd78d0703afafaffd94d8ccabda10c7b12d54cc59ccbb97a7b7e8656')
build() {
    cd "${srcdir}/${pkgname}-${pkgver//_/-}"
    pnpm i
    sed '/snap/d;/deb/d' -i electron-builder.yml
    pnpm add builder-util-runtime debug ms sax fs-extra universalify graceful-fs jsonfile js-yaml lazy-val semver lru-cache conf
    pnpm run build:linux
}
package() {
    install -Dm755 "${srcdir}/${pkgname}.sh" "${pkgdir}/opt/${pkgname}/${pkgname}"
    cp -r "${srcdir}/${pkgname}-${pkgver//_/-}/dist/linux-unpacked/resources/"* "${pkgdir}/opt/${pkgname}"
    install -Dm644 "${srcdir}/${pkgname}-${pkgver//_/-}/resources/icon.png" "${pkgdir}/usr/share/pixmaps/${pkgname}.png"
    gendesk -f -n --icon "${pkgname}" --categories "Utility" --name "${pkgname}" --exec "/opt/${pkgname}/${pkgname}"
    install -Dm644 "${srcdir}/${pkgname}.desktop" -t "${pkgdir}/usr/share/applications"
}
```
其中，`pnpm add`部分是编译完成后，运行编译完成的文件(运行编译好的AppImage文件也报同样的错误)，会报缺少模块的错，然后我手动添加的：
```
$ ./src/revezone-1.0.0-alpha.2/dist/linux-unpacked/revenote
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'lru-cache'
Require stack:
```
添加完成相关模块之后进行编译，新的错误出来了：
```
$ ./src/revezone-1.0.0-alpha.11/dist/linux-unpacked/revezone
A JavaScript error occurred in the main process
Uncaught Exception:
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/zxp-endeavouros/.cache/paru/clone/revezone/src/revezone-1.0.0-alpha.11/dist/linux-unpacked/resources/app.asar/node_modules/conf/dist/source/index.js from /home/zxp-endeavouros/.cache/paru/clone/revezone/src/revezone-1.0.0-alpha.11/dist/linux-unpacked/resources/app.asar/node_modules/electron-store/index.js not supported.
Instead change the require of /home/zxp-endeavouros/.cache/paru/clone/revezone/src/revezone-1.0.0-alpha.11/dist/linux-unpacked/resources/app.asar/node_modules/conf/dist/source/index.js in /home/zxp-endeavouros/.cache/paru/clone/revezone/src/revezone-1.0.0-alpha.11/dist/linux-unpacked/resources/app.asar/node_modules/electron-store/index.js to a dynamic import() which is available in all CommonJS modules.
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Object.<anonymous> (/home/zxp-endeavouros/.cache/paru/clone/revezone/src/revezone-1.0.0-alpha.11/dist/linux-unpacked/resources/app.asar/node_modules/electron-store/index.js:4:14)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at require (/home/zxp-endeavouros/.cache/paru/clone/revezone/src/revezone-1.0.0-alpha.11/dist/linux-unpacked/resources/app.asar/out/main/bytecode-loader.js:53:19)
    at Object.<anonymous> (evalmachine.<anonymous>:1:317)
    at Module._extensions..jsc (/home/zxp-endeavouros/.cache/paru/clone/revezone/src/revezone-1.0.0-alpha.11/dist/linux-unpacked/resources/app.asar/out/main/bytecode-loader.js:71:26)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Object.<anonymous> (/home/zxp-endeavouros/.cache/paru/clone/revezone/src/revezone-1.0.0-alpha.11/dist/linux-unpacked/resources/app.asar/out/main/index.js:3:1)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at node:electron/js2c/browser_init:2:123492
    at node:electron/js2c/browser_init:2:123695
    at node:electron/js2c/browser_init:2:123699
    at f._load (node:electron/js2c/asar_bundle:2:13330)
```
这些彻底就把人难住了~~~

**Comment by zxp19821005** [comment]
我本人不是程序员，所以只能病急乱投医了，百度第一条报错信息就是so的：https://stackoverflow.com/questions/76037548/uncaught-typeerror-lru-is-not-a-constructor-when-trying-to-connect-to-a-mysql，涉及到代码层面的，就看不懂了~

**Comment by zxp19821005** [comment]
另：能否声明一下License类型？比如 MIT GPL AGPL等

**Comment by korbinzhao** [comment]
感谢反馈。linux 版本的暂时没支持到，我研究支持下哈。License 晚些补充。

**Comment by zxp19821005** [comment]
新问题出现了：
### 直接运行编译后的文件
```
$ ./src/revezone-1.0.0-alpha.5/dist/linux-unpacked/revezone 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'builder-util-runtime'
Require stack:
- /home/zxp-endeavouros/.cache/paru/clone/revezone/src/revezone-1.0.0-alpha.5/dist/linux-unpacked/resources/app.asar/node_modules/electron-updater/out/main.js
- /home/zxp-endeavouros/.cache/paru/clone/revezone/src/revezone-1.0.0-alpha.5/dist/linux-unpacked/resources/app.asar/out/main/index.jsc
- /home/zxp-endeavouros/.cache/paru/clone/revezone/src/revezone-1.0.0-alpha.5/dist/linux-unpacked/resources/app.asar/out/main/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:117469)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/zxp-endeavouros/.cache/paru/clone/revezone/src/revezone-1.0.0-alpha.5/dist/linux-unpacked/resources/app.asar/node_modules/electron-updater/out/main.js:4:32)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
[169738:0815/133050.599788:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
^C%                                                                                                                                                                                                

# zxp-endeavouros @ 3993EndeavourOS in ~/.cache/paru/clone/revezone on git:master x [13:30:51] 
$ ./src/revezone-1.0.0-alpha.5/dist/revezone-1.0.0-alpha.2.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'builder-util-runtime'
Require stack:
- /tmp/.mount_revezoyTdTE4/resources/app.asar/node_modules/electron-updater/out/main.js
- /tmp/.mount_revezoyTdTE4/resources/app.asar/out/main/index.jsc
- /tmp/.mount_revezoyTdTE4/resources/app.asar/out/main/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:117469)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/tmp/.mount_revezoyTdTE4/resources/app.asar/node_modules/electron-updater/out/main.js:4:32)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
```
### 直接运行编译后的AppImage文件
```
 ./src/revezone-1.0.0-alpha.5/dist/revezone-1.0.0-alpha.2.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'builder-util-runtime'
Require stack:
- /tmp/.mount_revezoyTdTE4/resources/app.asar/node_modules/electron-updater/out/main.js
- /tmp/.mount_revezoyTdTE4/resources/app.asar/out/main/index.jsc
- /tmp/.mount_revezoyTdTE4/resources/app.asar/out/main/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:117469)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/tmp/.mount_revezoyTdTE4/resources/app.asar/node_modules/electron-updater/out/main.js:4:32)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
```

**Comment by zxp19821005** [comment]
最新版的[1.0.0-alpha.5](https://github.com/revezone/revezone/archive/refs/tags/1.0.0-alpha.5.tar.gz)中的package.json的文件版本还是1.0.0-alpha.2

**Comment by zxp19821005** [comment]
```
$ ./src/revezone-1.0.0-alpha.11/dist/revezone-1.0.0-alpha.7-x86_64.AppImage    
A JavaScript error occurred in the main process
Uncaught Exception:
Error [ERR_REQUIRE_ESM]: require() of ES Module /tmp/.mount_revezoNBLnpn/resources/app.asar/node_modules/conf/dist/source/index.js from /tmp/.mount_revezoNBLnpn/resources/app.asar/node_modules/electron-store/index.js not supported.
Instead change the require of /tmp/.mount_revezoNBLnpn/resources/app.asar/node_modules/conf/dist/source/index.js in /tmp/.mount_revezoNBLnpn/resources/app.asar/node_modules/electron-store/index.js to a dynamic import() which is available in all CommonJS modules.
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Object.<anonymous> (/tmp/.mount_revezoNBLnpn/resources/app.asar/node_modules/electron-store/index.js:4:14)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at require (/tmp/.mount_revezoNBLnpn/resources/app.asar/out/main/bytecode-loader.js:53:19)
    at Object.<anonymous> (evalmachine.<anonymous>:1:317)
    at Module._extensions..jsc (/tmp/.mount_revezoNBLnpn/resources/app.asar/out/main/bytecode-loader.js:71:26)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Object.<anonymous> (/tmp/.mount_revezoNBLnpn/resources/app.asar/out/main/index.js:3:1)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at node:electron/js2c/browser_init:2:123492
    at node:electron/js2c/browser_init:2:123695
    at node:electron/js2c/browser_init:2:123699
    at f._load (node:electron/js2c/asar_bundle:2:13330)
```
